## Movie Recomodation Proeject

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [5]:
df = pd.read_csv('movies_metadata.csv')
df.head()

   adult  ... vote_count
0  False  ...     5415.0
1  False  ...     2413.0
2  False  ...       92.0
3  False  ...       34.0
4  False  ...      173.0

[5 rows x 24 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [7]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [8]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [9]:
df = df.drop_duplicates().reset_index(drop = True)

In [10]:
df1 = df[['title','overview','genres','tagline','vote_average','popularity']].copy()

In [11]:
df1.head()

                         title  ... popularity
0                    Toy Story  ...  21.946943
1                      Jumanji  ...  17.015539
2             Grumpier Old Men  ...    11.7129
3            Waiting to Exhale  ...   3.859495
4  Father of the Bride Part II  ...   8.387519

[5 rows x 6 columns]

In [12]:
df1.isnull().sum()

title               6
overview          954
genres              0
tagline         25045
vote_average        6
popularity          5
dtype: int64

In [13]:
df1 = df1.dropna(subset =['title'])

In [14]:
df1['overview'] = df1['overview'].fillna('')

In [15]:
df1.isnull().sum()

title               0
overview            0
genres              0
tagline         25039
vote_average        0
popularity          0
dtype: int64

In [16]:
df1.iloc[0]['genres']
import ast

In [17]:
df1['genres'] = df1['genres'].apply(lambda x :" ".join([i['name'] for i in ast.literal_eval(x)]))

In [18]:
df1.head()

                         title  ... popularity
0                    Toy Story  ...  21.946943
1                      Jumanji  ...  17.015539
2             Grumpier Old Men  ...    11.7129
3            Waiting to Exhale  ...   3.859495
4  Father of the Bride Part II  ...   8.387519

[5 rows x 6 columns]

In [19]:
df1['tagline'] = df1['tagline'].fillna('')

In [20]:
df1.head()

                         title  ... popularity
0                    Toy Story  ...  21.946943
1                      Jumanji  ...  17.015539
2             Grumpier Old Men  ...    11.7129
3            Waiting to Exhale  ...   3.859495
4  Father of the Bride Part II  ...   8.387519

[5 rows x 6 columns]

In [21]:
df1.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

### Using NLP to convert the data into token or chunk and embedding

In [22]:
df1['tags'] = df1['overview']+' ' + df1['genres']+ " " + df1['tagline']

In [23]:
df1

                             title  ...                                               tags
0                        Toy Story  ...  Led by Woody, Andy's toys live happily in his ...
1                          Jumanji  ...  When siblings Judy and Peter discover an encha...
2                 Grumpier Old Men  ...  A family wedding reignites the ancient feud be...
3                Waiting to Exhale  ...  Cheated on, mistreated and stepped on, the wom...
4      Father of the Bride Part II  ...  Just when George Banks has recovered from his ...
...                            ...  ...                                                ...
45448                       Subdue  ...  Rising and falling between a man and woman. Dr...
45449          Century of Birthing  ...  An artist struggles to finish his work while a...
45450                     Betrayal  ...  When one of her hits goes wrong, a professiona...
45451             Satan Triumphant  ...  In a small town live two brothers, one a minis...
45452                     Queerama  ...  50 years after decriminalisation of homosexual...

[45447 rows x 7 columns]

In [24]:
df1['tags'][0]

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. Animation Comedy Family "

In [25]:
# removing the punctuation because it no meaning in contest and remove stopword (a i the and with or etc) nlp
# and reomoving leminization 

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [26]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\deppa\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\deppa\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [27]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [28]:
def preprocess_text(text):
    text = str(text).lower() # convert all text in lower cas (small letter)
    text = re.sub(r'[^a-zA-Z\s]','',text)  # remove the punctuation in text words
    
    words = text.split() # all word is split into single text 
    
    words = [word for word in words if word not in stop_words] # all word are remove stopword 
    
    # lemmatizes 
    words = [lemmatizer.lemmatize(word)for word in words ]
    
    return " ".join(words)

In [29]:
df1['tags'] = df1['tags'].apply(preprocess_text)

In [30]:
df1['tags'].head()

0    led woody andys toy live happily room andys bi...
1    sibling judy peter discover enchanted board ga...
2    family wedding reignites ancient feud nextdoor...
3    cheated mistreated stepped woman holding breat...
4    george bank recovered daughter wedding receive...
Name: tags, dtype: object

In [31]:
df1['tags'][0]

'led woody andys toy live happily room andys birthday brings buzz lightyear onto scene afraid losing place andys heart woody plot buzz circumstance separate buzz woody owner duo eventually learns put aside difference animation comedy family'

In [32]:
df1 = df1.reset_index(drop=True)

In [33]:
df1.head()

                         title  ...                                               tags
0                    Toy Story  ...  led woody andys toy live happily room andys bi...
1                      Jumanji  ...  sibling judy peter discover enchanted board ga...
2             Grumpier Old Men  ...  family wedding reignites ancient feud nextdoor...
3            Waiting to Exhale  ...  cheated mistreated stepped woman holding breat...
4  Father of the Bride Part II  ...  george bank recovered daughter wedding receive...

[5 rows x 7 columns]

In [34]:
indices = pd.Series(df1.index,index = df1['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [35]:
## All text converted into vector or embedding(numeric)

from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

tfidf = TfidfVectorizer(max_features=50000, stop_words='english',ngram_range=(1,2))

In [36]:
tfidf_matrix = tfidf.fit_transform(df1['tags'])

In [37]:
tfidf_matrix

<45447x50000 sparse matrix of type '<class 'numpy.float64'>'
	with 1548416 stored elements in Compressed Sparse Row format>

In [38]:
# checking cosine similarity to chek tidf uasing to chek tags feature

In [39]:
from sklearn.metrics.pairwise import cosine_similarity

def recommend(title,n = 10):
    if title not in indices:
        return ['Movies not found']
    
    idx = indices[title]
    sim_score = cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
    similar_idx = sim_score.argsort()[::-1][1:n+1]
    return df['title'].iloc[similar_idx]

In [ ]:
recommend('Toy Story')

2996                Toy Story 2
15344               Toy Story 3
24512         Hawaiian Vacation
28972            The First Star
17184                 Group Sex
6434     What's Up, Tiger Lily?
11396    For Your Consideration
1931                  Condorman
1071      Rebel Without a Cause
485                      Malice
Name: title, dtype: object

In [41]:
recommend('End Game')

26497    The Thirteen Assassins
8840             Boy Meets Girl
657               Bloodsport II
10328     The Constant Gardener
33880      Bikini Model Academy
4110        Along Came a Spider
37214         Rot ist die Liebe
40785                   Cloud 9
31362                     Helen
19925               Interceptor
Name: title, dtype: object

In [ ]:
# Generate to ui for this recommedation

In [42]:
import pickle 

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))

pickle.dump(indices,open('indices.pkl','wb'))

df.to_pickle('df.pkl')

pickle.dump(tfidf,open('tfidf.pkl','wb'))